# Generated by Django 5.2.15 on 2026-06-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nom")),
                ("email", models.EmailField(max_length=254, verbose_name="Courriel")),
                (
                    "subject",
                    models.CharField(blank=True, max_length=160, verbose_name="Sujet"),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Reçu le"),
                ),
                (
                    "is_handled",
                    models.BooleanField(default=False, verbose_name="Traité"),
                ),
            ],
            options={
                "verbose_name": "Message de contact",
                "verbose_name_plural": "Messages de contact",
                "ordering": ["-created_at"],
            },
        ),
    ]
