# Generated by Django 5.2.15 on 2026-06-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nom")),
                ("email", models.EmailField(max_length=254, verbose_name="Courriel")),
                (
                    "subject",
                    models.CharField(blank=True, max_length=160, verbose_name="Sujet"),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Reçu le"),
                ),
                (
                    "is_handled",
                    models.BooleanField(default=False, verbose_name="Traité"),
                ),
            ],
            options={
                "verbose_name": "Message de contact",
                "verbose_name_plural": "Messages de contact",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Founder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nom")),
                (
                    "role",
                    models.CharField(blank=True, max_length=120, verbose_name="Rôle"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Présentation")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="founders/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Affiché"),
                ),
            ],
            options={
                "verbose_name": "Fondateur·rice / équipe",
                "verbose_name_plural": "Fondateur·rices / équipe",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Nom")),
                ("url", models.URLField(blank=True, verbose_name="Site web")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="partners/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Affiché"),
                ),
            ],
            options={
                "verbose_name": "Partenaire",
                "verbose_name_plural": "Partenaires",
                "ordering": ["order", "name"],
            },
        ),
    ]
