# Generated by Django 5.2.15 on 2026-06-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="founder",
            name="name",
            field=models.CharField(blank=True, max_length=120, verbose_name="Nom"),
        ),
    ]
