# Generated by Django 5.2.15 on 2026-06-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="Titre")),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                (
                    "host_type",
                    models.CharField(
                        choices=[
                            ("school", "École"),
                            ("camp", "Camp d'été"),
                            ("community", "Organisme communautaire"),
                            ("other", "Autre lieu partenaire"),
                        ],
                        default="school",
                        max_length=12,
                        verbose_name="Type de lieu",
                    ),
                ),
                (
                    "location_name",
                    models.CharField(blank=True, max_length=160, verbose_name="Lieu"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=120, verbose_name="Ville"),
                ),
                (
                    "audience",
                    models.CharField(
                        blank=True,
                        help_text="Ex. : jeunes de 12 à 17 ans, groupe communautaire…",
                        max_length=160,
                        verbose_name="Public visé",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="workshops/",
                        verbose_name="Image",
                    ),
                ),
                ("starts_at", models.DateTimeField(verbose_name="Date et heure")),
                (
                    "ends_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fin"),
                ),
                (
                    "registration_url",
                    models.URLField(blank=True, verbose_name="Lien d'inscription"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
            ],
            options={
                "verbose_name": "Atelier",
                "verbose_name_plural": "Ateliers",
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkshopRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(max_length=180, verbose_name="Nom de l'organisme"),
                ),
                (
                    "host_type",
                    models.CharField(
                        choices=[
                            ("school", "École"),
                            ("camp", "Camp d'été"),
                            ("community", "Organisme communautaire"),
                            ("other", "Autre lieu partenaire"),
                        ],
                        default="school",
                        max_length=12,
                        verbose_name="Type de lieu",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=120, verbose_name="Personne-ressource"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Courriel")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Téléphone"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=120, verbose_name="Ville"),
                ),
                (
                    "audience",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Participants pressentis",
                    ),
                ),
                (
                    "preferred_dates",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Dates souhaitées"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, verbose_name="Votre projet / vos besoins"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouvelle"),
                            ("contacted", "Contact établi"),
                            ("scheduled", "Planifié"),
                            ("declined", "Refusé"),
                        ],
                        default="new",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Demande d'atelier",
                "verbose_name_plural": "Demandes d'atelier",
                "ordering": ["-created_at"],
            },
        ),
    ]
