# Generated by Django 5.2.15 on 2026-06-20 16:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nom affiché")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=140,
                        unique=True,
                        verbose_name="Identifiant URL",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Ex. : Autrice invitée, Collectif, Bénévole…",
                        max_length=120,
                        verbose_name="Rôle / titre",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biographie")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="authors/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Courriel (facultatif)"
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, verbose_name="Site / réseau (facultatif)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Auteur·rice",
                "verbose_name_plural": "Auteur·rices",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="Nom"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=90,
                        unique=True,
                        verbose_name="Identifiant URL",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="Description courte"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#1c5c49", max_length=7, verbose_name="Couleur (hex)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=220,
                        unique=True,
                        verbose_name="Identifiant URL",
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Court résumé affiché dans les listes et l'aperçu.",
                        max_length=320,
                        verbose_name="Chapeau / résumé",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Séparez les paragraphes par une ligne vide.",
                        verbose_name="Contenu",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="articles/",
                        verbose_name="Image de couverture",
                    ),
                ),
                (
                    "cover_credit",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Crédit photo"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Publié"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="À la une"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de publication",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="submissions.submission",
                        verbose_name="Issu de la soumission",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="blog.author",
                        verbose_name="Auteur·rice",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="blog.category",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(
                        fields=["-published_at"], name="blog_articl_publish_308f23_idx"
                    )
                ],
            },
        ),
    ]
