# Generated by Django 5.2.15 on 2026-06-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content_warning",
            field=models.CharField(
                blank=True,
                help_text="Si l'article aborde un sujet sensible (suicide, automutilation, violence…), nommez-le ici. Un encadré bienveillant s'affichera avant le texte.",
                max_length=200,
                verbose_name="Avertissement de contenu",
            ),
        ),
    ]
