# Generated by Django 5.2.15 on 2026-06-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        blank=True,
                        help_text="Facultatif — par ex. « anxiété », « rupture », « solitude ».",
                        max_length=160,
                        verbose_name="Sujet / thème",
                    ),
                ),
                (
                    "feeling",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        verbose_name="Comment te sens-tu en ce moment ?",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Une situation, une question ou un malaise. Tu restes anonyme.",
                        verbose_name="Ce que tu souhaites partager",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Courriel (facultatif)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouvelle"),
                            ("in_review", "En traitement"),
                            ("published", "A inspiré un article"),
                            ("archived", "Archivée"),
                        ],
                        default="new",
                        max_length=12,
                    ),
                ),
                (
                    "moderator_notes",
                    models.TextField(blank=True, verbose_name="Notes de modération"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Reçue le"),
                ),
            ],
            options={
                "verbose_name": "Soumission anonyme",
                "verbose_name_plural": "Soumissions anonymes",
                "ordering": ["-created_at"],
            },
        ),
    ]
