# Generated by Django 5.2.15 on 2026-06-20 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResourceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Situation")),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="Description courte"
                    ),
                ),
                (
                    "is_urgent",
                    models.BooleanField(
                        default=False, verbose_name="Situation d'urgence"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
            ],
            options={
                "verbose_name": "Catégorie de ressource",
                "verbose_name_plural": "Catégories de ressources",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Téléphone"
                    ),
                ),
                (
                    "text_number",
                    models.CharField(blank=True, max_length=60, verbose_name="Texto"),
                ),
                ("url", models.URLField(blank=True, verbose_name="Site web")),
                (
                    "availability",
                    models.CharField(
                        blank=True,
                        help_text="Ex. : 24 h/24, 7 j/7",
                        max_length=120,
                        verbose_name="Disponibilité",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Ex. : Canada, Québec…",
                        max_length=120,
                        verbose_name="Région",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Affiché"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="resources.resourcecategory",
                        verbose_name="Situation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ressource",
                "verbose_name_plural": "Ressources",
                "ordering": ["order", "name"],
            },
        ),
    ]
